<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251214150442 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE course (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, credits INT NOT NULL, teacher_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_169E6FB941807E1D ON course (teacher_id)');
        $this->addSql('CREATE TABLE enrollment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, grade NUMERIC(3, 2) DEFAULT NULL, enrolled_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, student_id INT DEFAULT NULL, course_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DBDCD7E1CB944F1A ON enrollment (student_id)');
        $this->addSql('CREATE INDEX IDX_DBDCD7E1591CC992 ON enrollment (course_id)');
        $this->addSql('CREATE TABLE exam (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, exam_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, grades VARCHAR(255) NOT NULL, course_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_38BBA6C6591CC992 ON exam (course_id)');
        $this->addSql('CREATE TABLE exam_student (exam_id INT NOT NULL, student_id INT NOT NULL, PRIMARY KEY (exam_id, student_id))');
        $this->addSql('CREATE INDEX IDX_BA85F65B578D5E91 ON exam_student (exam_id)');
        $this->addSql('CREATE INDEX IDX_BA85F65BCB944F1A ON exam_student (student_id)');
        $this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(10, 2) NOT NULL, status VARCHAR(20) NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, student_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6D28840DCB944F1A ON payment (student_id)');
        $this->addSql('CREATE TABLE shedule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, room VARCHAR(50) NOT NULL, time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, course_id INT DEFAULT NULL, teacher_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E7771B51591CC992 ON shedule (course_id)');
        $this->addSql('CREATE INDEX IDX_E7771B5141807E1D ON shedule (teacher_id)');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB941807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id)');
        $this->addSql('ALTER TABLE enrollment ADD CONSTRAINT FK_DBDCD7E1CB944F1A FOREIGN KEY (student_id) REFERENCES student (id)');
        $this->addSql('ALTER TABLE enrollment ADD CONSTRAINT FK_DBDCD7E1591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE exam ADD CONSTRAINT FK_38BBA6C6591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE exam_student ADD CONSTRAINT FK_BA85F65B578D5E91 FOREIGN KEY (exam_id) REFERENCES exam (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE exam_student ADD CONSTRAINT FK_BA85F65BCB944F1A FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DCB944F1A FOREIGN KEY (student_id) REFERENCES student (id)');
        $this->addSql('ALTER TABLE shedule ADD CONSTRAINT FK_E7771B51591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE shedule ADD CONSTRAINT FK_E7771B5141807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id)');
        $this->addSql('ALTER TABLE student DROP student');
        $this->addSql('ALTER TABLE student ALTER fullname SET NOT NULL');
        $this->addSql('ALTER TABLE student ALTER email SET NOT NULL');
        $this->addSql('ALTER TABLE student ALTER status SET NOT NULL');
        $this->addSql('ALTER TABLE teacher ALTER fullname SET NOT NULL');
        $this->addSql('ALTER TABLE teacher ALTER department SET NOT NULL');
        $this->addSql('ALTER TABLE teacher ALTER position SET NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE course DROP CONSTRAINT FK_169E6FB941807E1D');
        $this->addSql('ALTER TABLE enrollment DROP CONSTRAINT FK_DBDCD7E1CB944F1A');
        $this->addSql('ALTER TABLE enrollment DROP CONSTRAINT FK_DBDCD7E1591CC992');
        $this->addSql('ALTER TABLE exam DROP CONSTRAINT FK_38BBA6C6591CC992');
        $this->addSql('ALTER TABLE exam_student DROP CONSTRAINT FK_BA85F65B578D5E91');
        $this->addSql('ALTER TABLE exam_student DROP CONSTRAINT FK_BA85F65BCB944F1A');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840DCB944F1A');
        $this->addSql('ALTER TABLE shedule DROP CONSTRAINT FK_E7771B51591CC992');
        $this->addSql('ALTER TABLE shedule DROP CONSTRAINT FK_E7771B5141807E1D');
        $this->addSql('DROP TABLE course');
        $this->addSql('DROP TABLE enrollment');
        $this->addSql('DROP TABLE exam');
        $this->addSql('DROP TABLE exam_student');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE shedule');
        $this->addSql('ALTER TABLE student ADD student VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE student ALTER fullname DROP NOT NULL');
        $this->addSql('ALTER TABLE student ALTER email DROP NOT NULL');
        $this->addSql('ALTER TABLE student ALTER status DROP NOT NULL');
        $this->addSql('ALTER TABLE teacher ALTER fullname DROP NOT NULL');
        $this->addSql('ALTER TABLE teacher ALTER department DROP NOT NULL');
        $this->addSql('ALTER TABLE teacher ALTER "position" DROP NOT NULL');
    }
}
